# Copied from https://git.elc.cs.yonsei.ac.kr/byungukmin/shm_sync_latest/blob/70658f8da0af1f70d759b4bcad2864953a787192/cmake/Modules/FindLikwid.cmake

set(LIKWID_ROOT "" CACHE STRING "Location of LIKWID installation")

FIND_PATH(LIKWID_INCLUDE_DIR likwid.h HINTS ${LIKWID_ROOT}/include)
FIND_LIBRARY(LIKWID_LIBRARY likwid HINTS ${LIKWID_ROOT}/lib)
FIND_PROGRAM(LIKWID_PIN likwid-pin HINTS ${LIKWID_ROOT}/bin)

IF (LIKWID_INCLUDE_DIR AND LIKWID_LIBRARY)
  SET(LIKWID_FOUND TRUE)
ENDIF (LIKWID_INCLUDE_DIR AND LIKWID_LIBRARY)


IF (LIKWID_FOUND)
  IF (NOT LIKWID_FIND_QUIETLY)
    MESSAGE(STATUS "Found Likwid library: ${LIKWID_LIBRARY}")
    MESSAGE(STATUS "Found likwid-pin: ${LIKWID_PIN}")
  ENDIF (NOT LIKWID_FIND_QUIETLY)
ELSE (LIKWID_FOUND)
  IF (LIKWID_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Likwid")
  ENDIF (LIKWID_FIND_REQUIRED)
ENDIF (LIKWID_FOUND)
